version: '3'

services:
  frontend:
    build: laravel
    ports:
      - 8888:80
    volumes:
      - ./src/sample:/var/www/html
    working_dir: /var/www/html
    # 開発サーバー起動
    command: php artisan serve --port 80 --host 0.0.0.0
