version: '3'

services:
  frontend:
    build: laravel
    ports:
      - 8888:80
    volumes:
      - ./src/sample:/var/www/html
    working_dir: /var/www/html
    # 開発サーバー起動
    command: php artisan serve --port 80 --host 0.0.0.0

  backend:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: sample
      MARIADB_USER: memoadmin
      MARIADB_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8887:80
